language: android
branches:
  only:
    - master
before_script:
- wget https://dl-ssl.google.com/android/repository/build-tools_r21.0.2-linux.zip
- unzip build-tools_r21.0.2-linux.zip -d $ANDROID_HOME >> /dev/null
- mv $ANDROID_HOME/android-5.0 $ANDROID_HOME/build-tools/21.0.2
- rm gradlew
- wget https://raw.githubusercontent.com/google/iosched/master/gradlew
- chmod +x gradlew

script: ./gradlew :app:build
android:
  componenents:
  - build-tools-21.0.2
  - android-21
  - extra-android-support
  - extra-android-m2repository
