language: android
branches:
  only:
    - master
before_script:
- chmod +x gradlew

script: ./gradlew :app:build
android:
  componenents:
  - build-tools-21.0.2
  - android-21
  - extra-android-support
  - extra-android-m2repository
